const employees = [
    { id: 1, firstName: "Zoe", lastName: "Robins", departmentId: 1},
    { id: 2, firstName: "Madeleine", lastName: "Madden", departmentId: 1},
    { id: 2, firstName: "Josha", lastName: "Sadowski", departmentId: 2},
    { id: 4, firstName: "Kate", lastName: "Fleetwood", departmentId: 2},
    { id: 5, firstName: "Priyanka", lastName: "Bose", departmentId: 3},
    { id: 6, firstName: "Hammed", lastName: "Animashun", departmentId: 3},
    { id: 7, firstName: "Alvaro", lastName: "Morte", departmentId: 3},
    { id: 8, firstName: "Taylor", lastName: "Napier", departmentId: 3},
    { id: 9, firstName: "Alan", lastName: "Simmonds", departmentId: 3},
    { id: 10, firstName: "Gil", lastName: "Cardinal", departmentId: 4},
    { id: 11, firstName: "Richard", lastName: "J. Lewis", departmentId: 4},
    { id: 12, firstName: "Randy", lastName: "Bradshaw", departmentId: 5},
    { id: 13, firstName: "Tracey", lastName: "Cook", departmentId: 5},
    { id: 14, firstName: "Lubomir", lastName: "Mykytiuk", departmentId: 5},
    { id: 15, firstName: "Dakota", lastName: "House", departmentId: 6},
    { id: 16, firstName: "Lori", lastName: "Lea Okameh", departmentId: 6},
    { id: 17, firstName: "Renae", lastName: "Morrisseau", departmentId: 6},
    { id: 18, firstName: "Rick", lastName: "Belcourt", departmentId: 6},
    { id: 19, firstName: "Selina", lastName: "Hanusa", departmentId: 7},
    { id: 20, firstName: "Buffy", lastName: "Gaudry", departmentId: 7},
    { id: 21, firstName: "Shaneen", lastName: "Ann Fox", departmentId: 7},
    { id: 22, firstName: "Allan", lastName: "Little", departmentId: 7},
    { id: 23, firstName: "Danny", lastName: "Rabbit", departmentId: 7},
    { id: 24, firstName: "Jesse", lastName: "Ed Azure", departmentId: 8},
    { id: 25, firstName: "Stacy", lastName: "Da Silva", departmentId: 8},
    { id: 26, firstName: "Vladimir", lastName: "Valenta", departmentId: 8},
    { id: 27, firstName: "Samone", lastName: "Sayeses-Whitney", departmentId: 8},
    { id: 28, firstName: "Paul", lastName: "Coeur", departmentId: 8},
    { id: 29, firstName: "Graham", lastName: "Greene", departmentId: 9},
    { id: 30, firstName: "Sandika", lastName: "Evergeen", departmentId: 9},
    { id: 31, firstName: "Jennifer", lastName: "Rodriguez", departmentId: 9},
    { id: 32, firstName: "Aiyana", lastName: "Littlebear", departmentId: 10},
    { id: 33, firstName: "Inara", lastName: "Thunderbird", departmentId: 10},
    { id: 34, firstName: "Kaya", lastName: "Runningbrook", departmentId: 10},
    { id: 35, firstName: "Elara", lastName: "Firehawk", departmentId: 10},
    { id: 36, firstName: "Siona", lastName: "Moonflower", departmentId: 10},
    { id: 37, firstName: "Kaiyu", lastName: "Greywolf", departmentId: 10},
    { id: 38, firstName: "Ayawamat", lastName: "Nightwind", departmentId: 10},
    { id: 39, firstName: "Tala", lastName: "Braveheart", departmentId: 10},
    { id: 40, firstName: "Iniko", lastName: "Stonebear", departmentId: 10},
    { id: 41, firstName: "Onatah", lastName: "Redhawk", departmentId: 10}
]

export default employees;